services:
  salehero:
    container_name: salehero-container
    build: .
    ports:
      - "8880:8880"
    networks:
      - salehero-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod,secret
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: mysql-container
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Gkdgo9912!
      - MYSQL_DATABASE=dailysale
      - MYSQL_USER=dailysale
      - MYSQL_PASSWORD=Gkdgo9912!
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - salehero-network


  redis:
    container_name: redis-container
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass Gkdgo9912!
    volumes:
      - redis-data:/data
    networks:
      - salehero-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  salehero-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
