services:
  salehero:
    container_name: salehero-container
    build: .
    ports:
      - "8880:8880"
    networks:
      - salehero-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod,secret
    depends_on:
      - mysql
      - redis
  
  mysql:
    container_name: mysql-container
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Gkdgo9912!
      - MYSQL_DATABASE=dailysale
      - MYSQL_USER=dailysale
      - MYSQL_PASSWORD=Gkdgo9912!
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - salehero-network
  
  nginx:
    container_name: nginx-container
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:80"
      - "443:443"
    user: "0"
    volumes:
      - /salehero/app/nginx/conf:/etc/nginx/conf.d
      - /salehero/app/nginx.conf:/etc/nginx/nginx.conf
      - /salehero/salehero_fe/build:/usr/share/nginx/html
      - /salehero/app/certbot/conf:/etc/letsencrypt
      - /salehero/app/certbot/www:/var/www/certbot
      - /salehero/images:/salehero/images
      - /salehero/app/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
      - /salehero/app/main.conf:/etc/modsecurity.d/main.conf
    networks:
      - salehero-network
    depends_on:
      - salehero
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  redis:
    container_name: redis-container
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass Gkdgo9912!
    volumes:
      - redis-data:/data
    networks:
      - salehero-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - salehero-network
    entrypoint: "/bin/sh -c 'trap exit TERM; if [ ! -d /etc/letsencrypt/live/salehero.kr ]; then certbot certonly --webroot -w /var/www/certbot --email your-email@example.com -d salehero.kr -d www.salehero.kr -d image.salehero.kr --agree-tos --no-eff-email; fi; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  salehero-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: