spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: sar
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul
  sql:
    init:
      continue-on-error: 'true'
      mode: always
  redis:
    host: localhost
    port: 6379
    password:

target:
  origins: http://localhost:3000